title: Idaes Multi-Variant Optimization
author: Tyler R Jaffe
logo: ""

execute:
  execute_notebooks: "off"

sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
  config:
    bibtex_bibfiles:
      - references.bib
    html_theme: sphinx_book_theme
    html_theme_options:
      repository_url: "https://github.com/tjaffe-eng/tyler-idaes-mvo"
      repository_branch: "DEV_Package_Req_and_Install"
      launch_buttons:
        notebook_interface: jupyterlab
    exclude_patterns:
      - "_build"
      - ".myst"               # <--- Adding this to ignore the MyST JS cache folder
      - ".jupyter_cache"
