title: Idaes Multi-Variant Optimization
author: Tyler R Jaffe
logo: ""

execute:
  execute_notebooks: "off"

sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
  config:
    bibtex_bibfiles:
      - references.bib
    sys_path:
      - "../"
