title: Idaes Multi-Variant Optimization
author: Tyler R Jaffe
logo: ""

execute:
  execute_notebooks: "off"

myst:
  error_rules:
    - myst-file-loads

sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
  config:
    bibtex_bibfiles:
      - references.bib
    html_theme: sphinx_book_theme
    html_theme_options:
      repository_url: "https://github.com/yourusername/idaes_mvo"
      repository_branch: "main"
      launch_buttons:
        notebook_interface: jupyterlab
    exclude_patterns:
      - "_build"
